name: foundlost
description: A new Flutter project.

publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.0
  flutter_bloc: ^7.3.3
  oauth2_client: ^2.3.0
  uuid: ^3.0.5
  get_it: ^7.2.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  cached_network_image: ^3.1.0+1
  flutter_cache_manager: ^3.1.3
  flutter_i18n: ^0.30.0
  rxdart: ^0.27.3 
  image_picker: ^0.8.4+4
  geoflutterfire: 
    git: 
      url: https://github.com/giorgio79/GeoFlutterFire.git
  geocoding: ^2.0.1
  geolocator: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/es.json
    - assets/i18n/en.json

  
